### ISSUE TITLE
Suggeston: rain collection

### ISSUE THREAD

**Issue by wizard1399** [RCXcrafter/morebuckets#1]
Could you add a rain barrel to collect water when it is raining?

**Comment by RCXcrafter** [comment]
I'm sorry but that's not really what the mod is meant for, the only purpose is to add more buckets. However I'm pretty sure ex nihilo has a barrel that can collect rain.

**Comment by wizard1399** [comment]
I am really trying to avoid ex nihilo as every skyblock uses it. See a mod too often and it gets boring to watch and play.
