### ISSUE TITLE
Buckets in almost* every creative menu

### ISSUE THREAD

**Issue by Fortist** [RCXcrafter/morebuckets#2]
As the title says, almost* every creative menu, for all buckets and all liquids in buckets, and even the trash slot.

*Some mods seem to have a hold on their creative menus or you have some sort of script to add buckets to mods that have liquids into their creative menus. For example, Rustic Alchemy has the buckets, but another Rustic tab does not.

**Comment by RCXcrafter** [comment]
I forgot that you have to check if an item belongs in a tab now.
